### AUTOGRAD: AUTOMATIC DIFFERENTIATION

https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html

Document about autograd.Function is at https://pytorch.org/docs/stable/autograd.html#function

In [1]:
import torch

In [2]:
# .requires_grad_( ... ) changes an existing Tensor’s requires_grad flag in-place.
# The input flag defaults to False if not given.

a = torch.randn(2, 2)
a = ((a *3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [3]:
# Create a tensor and set requires_grad=True to track computation with it

x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [4]:
# Do a tensor operation:

y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [5]:
# y was created as a result of an operation, so it has a grad_fn.

print(y.grad_fn)

In [6]:
# Do more operations on y

z = y * y *3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [7]:
# Let’s backprop now. 
# Because out contains a single scalar, 
# out.backward() is equivalent to out.backward(torch.tensor(1.)).

out.backward()

In [8]:
# Print gradients d(out)/dx

print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [9]:
# Now let’s take a look at an example of vector-Jacobian product:

x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([  939.1310, -1375.9380,   120.2919], grad_fn=<MulBackward0>)


In [10]:
# Now in this case y is no longer a scalar. 
# torch.autograd could not compute the full Jacobian directly, 
# but if we just want the vector-Jacobian product, 
# simply pass the vector to backward as argument:

v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [11]:
# You can also stop autograd from tracking history on Tensors with .requires_grad=True 
# either by wrapping the code block in with torch.no_grad():

print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [12]:
# Or by using .detach() to get a new Tensor with the same content 
# but that does not require gradients:

print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)
