### WHAT IS PYTORCH?

https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

In [1]:
from __future__ import print_function
import torch

In [2]:
# Construct a 5x3 matrix, uninitialized:

x = torch.empty(5, 3)
print(x)

tensor([[5.6719e-11, 7.3471e+28, 2.6383e+23],
        [2.7376e+20, 1.8040e+28, 1.8750e-19],
        [7.3909e+22, 2.4176e-12, 2.6209e+20],
        [4.1641e+12, 8.9625e-01, 7.9309e+34],
        [7.9439e+08, 3.2604e-12, 7.3113e+34]])


In [3]:
# Construct a randomly initialized matrix:

x = torch.rand(5, 3)
print(x)

tensor([[0.7991, 0.3642, 0.5621],
        [0.9990, 0.7544, 0.4832],
        [0.9372, 0.6994, 0.9971],
        [0.0251, 0.3408, 0.1533],
        [0.7975, 0.1170, 0.3653]])


In [4]:
# Construct a matrix filled zeros and of dtype long:

x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# Construct a tensor directly from data:

x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)   # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                                               # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.6574,  0.2974, -2.0913],
        [-1.5059, -0.8401,  0.9795],
        [ 2.0227, -0.3183,  1.9995],
        [-0.3758,  1.5225,  0.5152],
        [ 0.5562,  0.7765, -1.9690]])


In [7]:
# Get its size:

print(x.size())
print(x.size(0))
print(x.size(1))

torch.Size([5, 3])
5
3


In [8]:
# Addition: syntax 1

y = torch.rand(5, 3)
print(x + y)

tensor([[-0.0884,  0.7887, -1.2902],
        [-1.2719, -0.5858,  1.3773],
        [ 2.3367,  0.6680,  2.4084],
        [ 0.1346,  2.3209,  1.2742],
        [ 1.0210,  1.4839, -1.2721]])


In [9]:
# Addition: syntax 2

print(torch.add(x, y))

tensor([[-0.0884,  0.7887, -1.2902],
        [-1.2719, -0.5858,  1.3773],
        [ 2.3367,  0.6680,  2.4084],
        [ 0.1346,  2.3209,  1.2742],
        [ 1.0210,  1.4839, -1.2721]])


In [10]:
# Addition: providing an output tensor as argument

result = torch.empty(5, 3)
print(result)
torch.add(x, y, out=result)
print(result)

tensor([[-7.2568e-07,  4.5743e-41, -7.2568e-07],
        [ 4.5743e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])
tensor([[-0.0884,  0.7887, -1.2902],
        [-1.2719, -0.5858,  1.3773],
        [ 2.3367,  0.6680,  2.4084],
        [ 0.1346,  2.3209,  1.2742],
        [ 1.0210,  1.4839, -1.2721]])


In [11]:
# Addition: in-place

# adds x to y
y.add_(x)
print(y)

tensor([[-0.0884,  0.7887, -1.2902],
        [-1.2719, -0.5858,  1.3773],
        [ 2.3367,  0.6680,  2.4084],
        [ 0.1346,  2.3209,  1.2742],
        [ 1.0210,  1.4839, -1.2721]])


In [12]:
# You can use standard NumPy-like indexing with all bells and whistles!

print(x)
print(x[:, 0])
print(x[0, :])

tensor([[-0.6574,  0.2974, -2.0913],
        [-1.5059, -0.8401,  0.9795],
        [ 2.0227, -0.3183,  1.9995],
        [-0.3758,  1.5225,  0.5152],
        [ 0.5562,  0.7765, -1.9690]])
tensor([-0.6574, -1.5059,  2.0227, -0.3758,  0.5562])
tensor([-0.6574,  0.2974, -2.0913])


In [13]:
# Resizing: If you want to resize/reshape tensor, you can use torch.view:

x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
z1 = x.view(-1, 16)
z2 = x.view(-1, 2)
print(x.size(), y.size(), z.size(), z1.size(), z2.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8]) torch.Size([1, 16]) torch.Size([8, 2])


In [14]:
# If you have a one element tensor, use .item() to get the value as a Python number

x = torch.randn(1)
print(x)
print(x.item())

tensor([1.3006])
1.3006131649017334


In [15]:
# Converting a Torch Tensor to a NumPy Array

a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [16]:
# See how the numpy array changed in value.

a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [17]:
#  Converting NumPy Array to Torch Tensor

import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [18]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if not torch.cuda.is_available():
    device = torch.device("cpu")                 # a CUDA device object
    print(device)
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))           # ``.to`` can also change dtype together!

cpu
tensor([2.3006])
tensor([2.3006], dtype=torch.float64)


In [19]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if not torch.cuda.is_available():
    device = torch.device("cuda")               # a CUDA device object
    print(device)
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))           # ``.to`` can also change dtype together!

cuda


AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx